#define T_IP                              1
#define T_COMMA                           2
#define T_AT                              3
#define T_DECLARE                         4
#define T_LBRACES                         5
#define T_RBRACES                         6
#define T_END_EXPR                        7
#define T_HOST_LABEL                      8
#define T_START                           9
#define T_STOP                           10
#define T_AFTER                          11
#define T_LPAREN                         12
#define T_NUMBER                         13
#define T_RPAREN                         14
#define T_DO                             15
#define T_WHILE                          16
#define T_IP_VAR                         17
#define T_DEVICE_VAR                     18
#define T_QUOTED_STRING                  19
#define T_ELSE                           20
#define T_IS_EQUAL                       21
#define T_IS_NOT_EQUAL                   22
#define T_IF                             23
#define T_THEN                           24
#define T_SET                            25
#define T_ARROW                          26
#define T_STRING                         27
#define T_FOR                            28
#define T_EACH                           29
#define T_END_IF                         30
#define T_END                            31
#define T_COLON                          32
#define T_DROP                           33
#define T_DUPLICATE                      34
#define T_DELAY                          35
#define T_PROGRESSIVE                    36
#define T_SCTP                           37
#define T_TCP                            38
#define T_UDP                            39
#define T_ALL                            40
#define T_PARTITION                      41
